### ISSUE TITLE
Mode "system" not reactive

### ISSUE THREAD

**Issue by toniengelhardt** [Eschricht/nuxt-color-mode#1]
This is epic, thanks for making it 🙏🏽

One thing I noticed is that if the mode is set to "system" and I toggle the preference of the OS, the module does not react. This works in the original module, but not sure if this is a bug or not possible due to the difference in implementation.

Hope this will make it into the main module eventually!

**Comment by Eschricht** [comment]
Thank you for the feedback!

Right, my module is currently only based on the returned response header.
I'll look into also getting the system color scheme from the browser this later this evening 👍

**Comment by toniengelhardt** [comment]
It also doesn't seem to work on iPhone / Chrome. The system preference is just ignored.

**Comment by Eschricht** [comment]
> It also doesn't seem to work on iPhone / Chrome. The system preference is just ignored.

Yes, unfortunately the `Sec-CH-Prefers-Color-Scheme` header is an experimental one and some browsers and systems doesn't support it.

Supported browsers can be found here
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-Prefers-Color-Scheme#browser_compatibility

However, when I've implemented getting the system color scheme from browser API as backup, it should work client side at least.

**Comment by toniengelhardt** [comment]
Would be amazing to get this into the main module.

If I'm not mistaken `@nuxtjs/color-mode` originally also used cookies, not sure why they moved away from it. Maybe something related to GDPR or so...

**Comment by Eschricht** [comment]
@toniengelhardt I've updated the package with some fixes regarding this issue (and also added force color mode).

It will make the system color scheme reactive so changing the system color mode will also update the application.

Regarding browsers not supporting the `Sec-CH-Prefers-Color-Scheme` header - there's not much to do about that more than hoping the browsers implement it. With that said, since the module now also check color mode though browser API so they will get the system color mode on client side (which will cause a brief flash if colors mismatch)

Appreciate your support!
I agree that it's a bit weird that `@nuxtjs/color-mode` is using Local Storage in favor of cookies.
Afaik Local Storage is considered a cookie in the sense of GDPR so I don't see why that should matter.

Anyways, hope this module will cut it for you (and me) until `@nuxtjs/color-mode` solves this.

**Comment by toniengelhardt** [comment]
Great work, deeply appreciate it 🙏🏽
